CREATE TABLE `user` (
  `id` varchar(64) CHARACTER SET utf8 NOT NULL COMMENT '编号',
  `company_id` varchar(64) CHARACTER SET utf8 DEFAULT NULL COMMENT '归属公司',
  `office_id` varchar(64) CHARACTER SET utf8 DEFAULT NULL COMMENT '归属部门',
  `login_name` varchar(100) CHARACTER SET utf8 DEFAULT NULL COMMENT '登录名',
  `password` varchar(100) CHARACTER SET utf8 DEFAULT NULL COMMENT '密码',
  `refund_password` varchar(100) CHARACTER SET utf8 DEFAULT NULL COMMENT '退款密码',
  `no` varchar(100) CHARACTER SET utf8 DEFAULT NULL COMMENT '工号',
  `name` varchar(100) CHARACTER SET utf8 DEFAULT NULL COMMENT '姓名',
  `email` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '邮箱',
  `phone` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '电话',
  `mobile` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '手机',
  `user_type` char(1) CHARACTER SET utf8 DEFAULT NULL COMMENT '用户类型',
  `photo` varchar(1000) CHARACTER SET utf8 DEFAULT NULL COMMENT '用户头像',
  `login_ip` varchar(100) CHARACTER SET utf8 DEFAULT NULL COMMENT '最后登陆IP',
  `login_date` datetime DEFAULT NULL COMMENT '最后登陆时间',
  `login_flag` varchar(64) CHARACTER SET utf8 DEFAULT NULL COMMENT '是否可登录',
  `create_by` varchar(64) CHARACTER SET utf8 DEFAULT NULL COMMENT '创建者',
  `create_date` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) CHARACTER SET utf8 DEFAULT NULL COMMENT '更新者',
  `update_date` datetime DEFAULT NULL COMMENT '更新时间',
  `remarks` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '备注信息',
  `del_flag` char(1) CHARACTER SET utf8 DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;